#define STORE_BUFFER_SIZE				2
#define MB_SIZE_IN_BYTES 				1048576
#define MAIN_STORE_SIZE 				512*MB_SIZE_IN_BYTES
#define GPU_MEMORY_ALLOC_ATTEMPTS 		4
#define STREAMS_NUM_UPLOAD				2
#define STREAMS_NUM_QUERY				2
