// BUFFERS
#define STORE_BUFFER_SIZE				256

// MAIN MEMORY SIZE
#define MB_SIZE_IN_BYTES 				1048576
#define MAIN_STORE_SIZE 				768*MB_SIZE_IN_BYTES
#define GPU_MEMORY_ALLOC_ATTEMPTS 		4

// STREAMS
#define QUERY_STREAMS_COUNT				20
#define INSERT_STREAMS_COUNT			20

// CUDA DEVICE REQUIREMENTS
#define MIN_CUDA_MAJOR_VER				2
#define MIN_CUDA_MINOR_VER				0

// THREADS
#define QUERY_THRED_POOL_SIZE			1000
#define INSERT_THRED_POOL_SIZE			1000
