#ifndef STORESETTINGS_H_
#define STORESETTINGS_H_

#define DEVICE_BUFFERS_COUNT 10
#define STORE_BUFFER_SIZE 	 128

// THREADS
#define QUERY_THRED_POOL_SIZE			1000
#define INSERT_THRED_POOL_SIZE			1000

#endif /* STORESETTINGS_H_ */
